name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:devel
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            cmake g++ qt6-base-dev libdtk6core-dev libdtk6gui-dev libdtk6widget-dev \
            libgtest-dev pkg-config
      - name: Configure
        env:
          CC: /usr/bin/gcc
          CXX: /usr/bin/g++
        run: cmake -B build -DBUILD_TESTING=ON
      - name: Build & test
        run: |
          cmake --build build -j"$(nproc)"
          ctest --test-dir build --output-on-failure
